Adding TestCases
wso2-extensions/siddhi-map-json pull request #25
Opened 2017-10-19 06:08 UTC by kalaiyarasiganeshalingam

## Purpose
Port test cases implemented in test hackathon to master branch

## Documentation
N/A

## Certification
N/A

## Automation tests
 - Unit tests 
   coverage-86%

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

2017-10-19 09:37 UTC, tishan89 requested changes

2017-10-19 09:37 UTC, tishan89 commented on component/src/test/java/org/wso2/extension/siddhi/map/json/sourcemapper/JsonSourceMapperTestCase.java
> +        log.info("test JsonSourceMapper with test json missing attribute");
Where is the assertion? If you do not get an exception try to assert log content. Else no point in having the test

2017-10-19 09:37 UTC, tishan89 commented on component/src/test/java/org/wso2/extension/siddhi/map/json/sourcemapper/JsonSourceMapperTestCase.java
> +    public void jsonSourceMapperTest16() throws InterruptedException {
Where is the assertion? If you do not get an exception try to assert log content. Else no point in having the test

2017-10-19 09:37 UTC, tishan89 commented on component/src/test/java/org/wso2/extension/siddhi/map/json/sourcemapper/JsonSourceMapperTestCase.java
> +    public void jsonSourceMapperTest19() throws InterruptedException {
assertion??

2017-10-19 09:37 UTC, tishan89 commented on component/src/test/java/org/wso2/extension/siddhi/map/json/sourcemapper/JsonSourceMapperTestCase.java
> +        log.info("test JsonSourceMapper with test Test values type boolean");
assertion?

2017-10-19 09:37 UTC, tishan89 commented on component/src/test/java/org/wso2/extension/siddhi/map/json/sourcemapper/JsonSourceMapperTestCase.java
> +    public void jsonSourceMapperTest() throws InterruptedException {
assertion

2017-10-20 05:37 UTC, tishan89 approved these changes

2017-10-20 05:37 UTC, merged

2018-04-06 08:26 UTC, muthulee commented on component/src/test/java/org/wso2/extension/siddhi/map/json/sourcemapper/JsonSourceMapperTestCase.java
> +        log.info("test JsonSourceMapper with test json object type");
Why no Asserstion?

2018-04-06 08:26 UTC, muthulee commented on component/src/test/java/org/wso2/extension/siddhi/map/json/sourcemapper/JsonSourceMapperTestCase.java
> +        log.info("test JsonSourceMapper with test Test values type boolean");
+1. We need assertions.

2018-04-11 05:35 UTC, Megala21 commented on component/src/test/java/org/wso2/extension/siddhi/map/json/sourcemapper/UnitTestAppender.java
> +public class UnitTestAppender extends AppenderSkeleton {
All the public classes should be having java doc comment