Fix: top-level field prefix with `@` cause path not found
wso2-extensions/siddhi-map-json pull request #58
Opened 2018-09-19 11:03 UTC by PChou

## Purpose

With custom mapping(using `@attribute`), and mapping a top-level field prefix with `@`, cause path not found. The root cause is that `@` in JsonPath is a keyword.

## Approach

Add `DEFAULT_JSON_MAPPING_PREFIX` before the user mapping field can fix this issue.

## Automation tests
 - Unit tests 
   `JsonSourceMapperTestCase.jsonSourceMapperTest7` show the case

2018-10-28 15:57 UTC, minudika requested changes

2018-10-28 15:57 UTC, minudika commented on component/src/main/java/org/wso2/extension/siddhi/map/json/sourcemapper/JsonSourceMapper.java
> +                this.mappingPositions[i] = new MappingPositionData(position, DEFAULT_JSON_MAPPING_PREFIX + attributeMapping.getMapping());
Line length exceeds 120 characters.  Please fix it.

2018-10-28 15:59 UTC, minudika commented
@PChou Thanks for your contribution.

I have requested a minor change. Please fix it. 
Then we can get this merged.

2018-10-30 07:46 UTC, PChou commented
@minudika ok, i fixed.

2018-10-30 09:37 UTC, minudika approved these changes

2018-10-30 09:37 UTC, merged